"""Offline Markdown reports from saved evidence; never imports a GPU runtime."""

import json
import os
from collections import defaultdict
from pathlib import Path

from .storage import RESULTS, ROOT, read_log


def read_json(path):
    return json.loads(path.read_text(encoding="utf-8"))


def cell(value):
    if value is None:
        return "not recorded"
    return str(value).replace("|", "\\|").replace("\r", " ").replace("\n", "<br>")


def number(value, digits=3):
    return "not recorded" if value is None else f"{value:.{digits}f}"


def milliseconds(value):
    return None if value is None else value * 1000


def table(headers, rows):
    return "\n".join([
        "| " + " | ".join(map(cell, headers)) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
        *("| " + " | ".join(map(cell, row)) + " |" for row in rows),
    ])


def outcome(row):
    note = row.get("note", "").lower()
    if "patch_failed" in note:
        return "patch rejected"
    failures = sorted({w.get("failure_code") for w in row.get("workloads", []) if w.get("failure_code")})
    if failures:
        return "failed: " + ", ".join(failures)
    if "interrupted" in note and row.get("guard") == "not_run":
        return "interrupted / recovered"
    if row.get("guard") != "pass":
        return "guard rejected"
    if row.get("kept"):
        return "kept"
    if note.startswith("failed after") and "repair" in note:
        return f"failed: unit tests after {row.get('repairs', 0)} repairs"
    if any(term in note for term in ("patch_failed", "failed", "rejected", "stopped", "does not match")):
        return "rejected / incomplete"
    return "measured, not kept" if row.get("geomean_tps") is not None else "validation / not kept"


def log_table(records, notes=False):
    headers = ["ID", "Proposer", "Item", "Outcome", "Local geomean tok/s", "GPU seconds"]
    if notes:
        headers += ["Workloads", "Note"]
    rows = []
    for row in records:
        values = [row["id"], row.get("proposer"), row.get("item"), outcome(row),
                  number(row.get("geomean_tps")), number(row.get("gpu_seconds"))]
        if notes:
            values += [", ".join(w["name"] for w in row.get("workloads", [])) or "none", row.get("note", "")]
        rows.append(values)
    return table(headers, rows)


def generate(results=RESULTS, docs=ROOT / "docs"):
    results, docs = Path(results), Path(docs)
    records = read_log(results)
    def source(path):
        return f"[{path.name}]({Path(os.path.relpath(path, docs)).as_posix()})"

    official_path = results / "dryft_runs.json"
    official = read_json(official_path).get("runs", []) if official_path.exists() else []
    run_paths = sorted((results / "runs").glob("*.json"))
    runs = [(path, read_json(path)) for path in run_paths]
    sections = ["# Results", "Generated by `py -3.11 -m neokernel report`. No GPU or network calls are made.",
                "Here `results/` means `neokernel/results/`. Local measurements, official scores and physics estimates are separate. "
                "Raw run files are local artifacts; the hand-kept Dryft record is versioned.",
                "## Official submissions", "Scores and ranks are historical snapshots, not current leaderboard positions. "
                "The public workload table does not determine the hidden-workload official score.",
                "Source: " + source(official_path) + "."]
    sections.append(table(["Submission", "Dryft run", "Official score", "Rank at capture", "Evidence"], [
        [r["label"], f"[{r['run_id']}]({r['url']})" if r.get("url") else r["run_id"], number(r.get("score"), 1), r.get("rank"), r.get("source")]
        for r in official]))
    official_rows = []
    for run in official:
        for name in ("public-0", "public-1", "public-2"):
            w = run.get("workloads", {}).get(name, {})
            official_rows.append([run["label"], run["run_id"], name,
                                  number(w.get("ttft_ms"), 2), number(w.get("tpot_ms"), 2),
                                  number(w.get("tps"), 1)])
    sections += ["## Public workload measurements on Dryft",
                 "Submission labels #11 and #18 identify engine stages. They do not turn local log #18's failed benchmark into an official pass.",
                 table(["Submission", "Dryft run", "Workload", "TTFT ms", "TPOT ms", "Tokens/s"], official_rows)]
    for run in official:
        if run.get("note"):
            sections.append(f"{run['run_id']}: {run['note']}")

    profiles = []
    for path in sorted(results.glob("*profile*.json")):
        profile = read_json(path)
        if "sum_kernel_ms" not in profile:
            continue  # Trace-only files are not additional measurements.
        label = ("#11 baseline" if "hand_rolled_profile_before_" in path.name else
                 "#18 hand-rolled" if "hand_rolled_profile_after_" in path.name else path.stem)
        count = profile.get("kernel_count")
        if count is None:
            count = sum(k["calls"] for k in profile.get("kernels", []))
        profiles.append([label, profile.get("gpu_tier"), profile.get("workload"), count,
                         number(profile.get("sum_kernel_ms")), number(profile.get("gap_ms")), source(path)])
    sections += ["## Decode profiles", "One warm decode step. Kernel time and gap include profiler overhead and are not latency gate inputs. "
                 "The paired before/after files measure the #11 baseline and #18 hand-rolled decode stages. "
                 "Unmeasured shapes are not interpolated.",
                 table(["Stage", "GPU", "Workload", "Kernels/step", "Kernel ms", "Gap ms", "Source"], profiles)]

    eligible = [(p, r) for p, r in runs if r.get("gpu_tier") == "H100" and r.get("eligible") and r.get("workloads")]
    complete = [(p, r) for p, r in eligible if len(r["workloads"]) >= 6]
    sections += ["## Physics estimates", "Bandwidth assumes 3.35 TB/s; prefill assumes 600 TFLOP/s. "
                 "Measured/floor is measured throughput divided by estimated floor throughput, not a hardware utilization measurement. "
                 "Local h-a/h-b/h-c are proxy shapes, not disclosed Dryft hidden shapes."]
    if complete or eligible:
        path, run = max(complete or eligible, key=lambda pair: (pair[1].get("ts") or "", pair[0].name))
        sections.append("Latest eligible full H100 run when available: " + source(path) + ".")
        sections.append(table(["Shape B/S/N", "Workload", "Step floor ms", "Prefill floor ms", "Decode floor ms",
                               "Floor tok/s", "Measured tok/s", "Measured/floor"], [
            [f"{w['batch']}/{w['S']}/{w['N']}", w["name"],
             number(milliseconds(w.get("floors", {}).get("step_floor_s"))),
             number(milliseconds(w.get("floors", {}).get("prefill_floor_s"))),
             number(milliseconds(w.get("floors", {}).get("decode_floor_s"))),
             number(w.get("floors", {}).get("floor_tps")), number(w.get("tps")),
             number(w.get("floors", {}).get("measured_to_floor_ratio"), 4)] for w in run["workloads"]]))
    else:
        sections.append("No eligible H100 measurement recorded.")
    sections += ["## Experiment log", "Source: " + source(results / "log.jsonl") + ". "
                 "Local geomeans use each row's selected workloads and GPU tier; they are not directly comparable across all rows. "
                 "Not kept does not necessarily mean failed. See [full notes](log.md).", log_table(records)]

    spend_path, setup_path = results / "spend.json", results / "setup.json"
    spend = read_json(spend_path) if spend_path.exists() else {}
    tiers = defaultdict(lambda: {"calls": 0, "seconds": 0.0, "usd": 0.0})
    for call in spend.get("calls", []):
        bucket = tiers[call["tier"]]
        bucket["calls"] += 1
        bucket["seconds"] += call.get("estimated_allocation_s", 0)
        bucket["usd"] += call["estimated_usd"]
    setup = read_json(setup_path) if setup_path.exists() else {}
    setup_usd = setup.get("estimated_usd", spend.get("setup_estimated_usd", 0))
    spend_rows = [[tier, b["calls"], number(b["seconds"]), number(b["usd"], 6)] for tier, b in sorted(tiers.items())]
    spend_rows += [["CPU setup", len(setup.get("attempts", [])), "not GPU allocation", number(setup_usd, 6)],
                   ["Total", "", "", number(setup_usd + sum(b["usd"] for b in tiers.values()), 6)]]
    sections += ["## Estimated spend", "Sources: " + source(spend_path) + " and " + source(setup_path) + ". "
                 "Tier estimates include associated CPU/RAM and allocation waits. These are ledger estimates, not invoices. "
                 "Setup is counted once; experiment GPU seconds must not be summed to infer spend.",
                 table(["Tier", "Calls", "Estimated allocation seconds", "Estimated USD"], spend_rows)]
    docs.mkdir(parents=True, exist_ok=True)
    (docs / "RESULTS.md").write_text("\n\n".join(sections) + "\n", encoding="utf-8")
    (docs / "log.md").write_text("# Experiment log\n\nGenerated by `py -3.11 -m neokernel report` from "
                                + source(results / "log.jsonl") + ". Notes are historical records; later outcomes do not rewrite earlier failures.\n\n"
                                + log_table(records, notes=True) + "\n", encoding="utf-8")
    return docs / "RESULTS.md", docs / "log.md"
